### ISSUE TITLE
Consider adding runtime-defined endianness

### ISSUE THREAD

**Issue by netvl** [BurntSushi/byteorder#41] opened 2016-02-01 19:45 UTC
Sometimes it is impossible to statically determine required endianness in advance. For example, TIFF image format defines endianness in the first byte of an input file, so it may be either big or little but which exactly is unknown statically. It would be nice if I could use `byteorder` for this task too.

**Comment by BurntSushi** [comment] 2016-02-01 19:51
@netvl Hmm, is there any particular reason why [`NativeEndian`](http://burntsushi.net/rustdoc/byteorder/type.NativeEndian.html) doesn't work for you? (This otherwise looks like a dupe of #18.)

**Comment by BurntSushi** [comment] 2016-02-01 19:53
@netvl Oh, I misread your question. I guess I'm not following. What code have you tried? You should be able to invoke either endianness by calling e.g., `BigEndian::read_u32` or `LittleEndian::read_u32`.

**Comment by netvl** [comment] 2016-02-02 08:11
I'd like to pass the actual endianness to read functions at runtime, something like
```rust
let byte_order = if <some check> { LittleEndian } else { BigEndian };
let n = source.read_u16(byte_order);
```

Here the required byte order is determined at runtime. I also can't use `ByteOrder` as a trait object because all its methods are static (and anyway, they don't work with `Read` directly).

**Comment by BurntSushi** [comment] 2016-02-02 12:30
@netvl Define some helper functions? e.g.,

```rust
enum Endian { Little, Big }

fn read_u16(source: &[u8], endian: Endian) -> byteorder::Result<u16> {
    match endian {
        Endian::Little => byteorder::LittleEndian::read_u16(source),
        Endian::Big => byteorder::BigEndian::read_u16(source),
    }
}

read_u16(&[...], Endian::Little)
```

**Comment by netvl** [comment] 2016-02-02 12:35
Well, yes, that's what I've done. I wrote an extension trait for `Read` and a macro which generates all the necessary methods. I just think that this should be provided by the library :)

**Comment by BurntSushi** [comment] 2016-02-02 12:37
@netvl I see. I'm not totally convinced the added API surface is really worth it ("I'm trying to use byteorder but there are three different ways to read a big endian number, which one should I use?"). I can see how they would be useful occasionally though.

**Comment by netvl** [comment] 2016-02-02 12:46
Maybe this problem is solved by the proper documentation. Something along the following lines:
> There are three ways to read a number in a specific endianness:
>  * by using methods of `ByteOrder` trait, like `BigEndian::read_u16(buf)`, if you need to read a number from a byte slice with a statically known byte order;
>  * by using methods of `ReadBytesExt` extension trait, like `source.read_u16::<BigEndian>()`, if you need to read a number from a `Read` instance with a statically known byte order;
>  * or by using methods of `ReadBytesDynamicExt` extension trait, like `source.read_u16(byte_order)`, if you need to read a number from a `Read` instance when the byte order is determined at runtime.

**Comment by BurntSushi** [comment] 2016-08-01 02:29
I still personally feel like expecting one to write a helper function for this is perfectly fine. I'd really rather not make the API more complex than it already is.

**Closed by BurntSushi** 2016-08-01 02:29 UTC
Labels: question
