### ISSUE TITLE
Need enum to choose big/little

### ISSUE THREAD

**Issue by damody** [BurntSushi/byteorder#124] opened 2018-05-03 09:55 UTC
like this
```rust
enum ByteOrder {
BigEndian,
LittleEndian,
}
```
then we can use the struct like parameter
like this
```rust
pub fn hello(order:ByteOrder) ->() {
    let mut rdr = Cursor::new(vec![2, 5, 3, 0]);
    match order {
    BigEndian => rdr.read_u16::<BigEndian>().unwrap();
    LittleEndian => rdr.read_u16::<LittleEndian>().unwrap();
    _=>()
    }
}
```

**Comment by BurntSushi** [comment] 2018-05-03 10:31
This issue is drastically under specified, and I believe it is a duplicate of #95.

**Closed by BurntSushi** 2018-05-03 10:31 UTC
